[build.environment]
HUGO_VERSION = "0.143.1"
NODE_VERSION = "22"
TZ = "America/New_York"

[build]
publish = "public"
command = "hugo --gc --minify"

[context.production]
command = "hugo --minify --baseURL https://ginatrapani.org/"

[context.deploy-preview]
command = "hugo --baseURL $DEPLOY_PRIME_URL"

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"
